// merge per sample counts generated by featureCounts into a combined table

process MERGE_FEATURECOUNTS {
    label "low"
    label "rscript"

    publishDir "${params.outdir}/featurecounts/", mode: "copy"

    input:
    // list of count files produced by featureCounts
    path count_files

    output:
    path "merged_gene_counts.txt"

    script:
    """
    #!/usr/bin/env Rscript

    files <- list.files(".", pattern = "\\\\.txt\$", full.names = TRUE)

    counts_list <- lapply(files, function(f) {
        df <- read.table(f, header=TRUE, comment.char="#", sep="\\t")
        sample <- sub("\\\\.geneCounts\\\\.txt\$", "", basename(f))
        setNames(df[, c("Geneid", colnames(df)[7])], c("Geneid", sample))
    })

    merged <- Reduce(function(x, y) merge(x, y, by="Geneid"), counts_list)
    write.table(merged, "merged_gene_counts.txt", sep="\\t", row.names=FALSE, quote=FALSE)
    """
}
